apiVersion: 1

datasources:
  - name: BigQuery
    type: grafana-bigquery-datasource
    access: proxy
    uid: bigquery-content-shield
    isDefault: true
    jsonData:
      authenticationType: gce
      defaultProject: ${GCP_PROJECT_ID}
      processingLocation: us-central1
    editable: false
